from setuptools import setup, find_packages

setup(
    name="pdf-extractor",
    version="0.1.0",
    packages=find_packages(),
    install_requires=[
        "PyQt5>=5.15.9",
        "PyQtWebEngine>=5.15.6",
        "pyqtdarktheme>=2.1.0",
        "matplotlib>=3.7.2",
        "seaborn>=0.12.2",
        "PyPDF2>=3.0.1",
        "pdfplumber>=0.9.0",
        "camelot-py>=0.10.1",
        "tabula-py>=2.7.0",
        "pdf2image>=1.16.3",
        "pytesseract>=0.3.10",
        "requests>=2.31.0",
        "beautifulsoup4>=4.12.2",
        "selenium>=4.11.2",
        "webdriver-manager>=3.8.6",
        "pandas>=2.0.3",
        "numpy>=1.24.3",
        "pydantic>=2.0.3",
        "marshmallow>=3.19.0",
        "scikit-learn>=1.3.0",
        "langdetect>=1.0.9",
        "sqlalchemy>=2.0.19",
        "tqdm>=4.65.0",
        "python-dotenv>=1.0.0",
        "pillow>=10.0.0",
        "opencv-python>=4.8.0.74",
    ],
    author="Seu Nome",
    author_email="seu.email@exemplo.com",
    description="Aplicativo para extração de dados de PDFs",
    keywords="pdf, extração, dados",
    python_requires=">=3.8",
)